### PR TITLE
A6, A7: Add undeclared variables, remove a test

### PR DESCRIPTION
**Pull request by Technius**
* Removed abekarplus-10 from A6 and A7 (see #16)
* Added `y` to the variable declarations in skylerbistarkeyrez-3,4 in A6 and A7 (it was being used without being declared)

### CODE REVIEW

**Comment by sidsenkumar11** [comment]
Seems good to me!

**Comment by aaabbbjj** [comment]
Hi,
Did you get the same results for test cases saagarjha-10, saagarjha-15, and saagarjha-16? There are the three cases that we have different results.

**Comment by sidsenkumar11** [comment]
What results are you getting? Currently my solution for all assignments matches what is in the master branch right now.

**Comment by aaabbbjj** [comment]
for 10, 15 we got 
x : {alloc4}
y : {alloc6}
Alloc10 : {}
Alloc4 : {alloc8}
Alloc6 : {alloc10}
Alloc8 : {}

**Comment by sidsenkumar11** [comment]
I looked over the 3 tests and realized they each have "projection = projection" statements (eg x.1 = y.1), which the professor said we should disallow. So I think we should remove these tests and solutions - good catch!

**Comment by aaabbbjj** [comment]
Sounds good! Thank you for checking.

**Comment by aaabbbjj** [comment]
Hi Sid, do you mind checking the williameiers-00,11,17 for hw7 cases? We got different results for those as well. Thank you!

**Comment by sidsenkumar11** [comment]
I worked those out by hand but I'm getting the same answers

**Pull request merged**
