### PR TITLE
Bugfixes in testsuite

### PR DESCRIPTION
**Pull request by Lukas-Dresel**
I have fixed bugs in most testcases so far.
Bugs included:

- formatting errors
- Incorrect answers
- Missing nodes
- Wrong node numbering
- Undefined variables

If there's disagreement on some of the changes please do it in the comments (annotations) so we can see which testcases, where, etc.

I now claim that the following testcases are correct (i got through them and agree with them):

- [x] abekarplus
- [x] chanijindal
- [x] DongyuMeng
- [x] fabio-gritti
- [x] kburk
- [x] lukasdresel
- [x] nemanja
- [x] saagarja
- [x] seemantasaha
- [x] siddarth
- [x] skylerbistarkeyrez
- [x] sydneyma
- [x] XiyouZhou
- [ ] YanjuChen

### CODE REVIEW

**Comment by zxybazh** [comment]
Hi, thanks for editing the testcases, can you please include the new commits and send a pull request with all testcases after your check. I would merge and let others check and comment in issues after wards. PS: in your forked branch, I noticed something weird in XiyouZhou-1.solution.

**Comment by Lukas-Dresel** [comment]
What do you mean? Do you mean seperate PRs for every commit? 
I just fixed the program showing up in the solution right now, thanks for noticing!

**Comment by Lukas-Dresel** [comment]
if you just wanna merge so that master has the right testcases, you should just be able to merge this PR. We can just discuss in issues afterwards then.

**Comment by Lukas-Dresel** [comment]
I'm not really sure what to do about YanjuChen's testcases, there's stuff like `Bottom` in the imp syntax. So I'll leave them as is for now. That can be fixed later.

**Comment by zxybazh** [comment]
OK, merging your testcases fix. Please send issues if there is any problem in the test suite.

**Comment by Lukas-Dresel** [comment]
Awesome!

**Comment by zxybazh** [comment]
About Yanju's test case...No worries, I'll let him know.

**Pull request merged**
