### PR TITLE
HW 1-4 Test Cases

### PR DESCRIPTION
**Pull request by sidsenkumar11**
**Before this gets merged into master, I'd like at least one other group to verify that they receive the exact same results. Thanks!**

I've made several changes to the test case solutions, and now I believe all the solutions for HW1-4 should be correct. However, it is very possible/likely that I made mistakes, so I would appreciate a peer review!

## Summary of Changes
Each of the following changes follows the commit order (so you can see the changes relatively easily).
- Renamed my group's tests to match the professor's convention (HW1, HW3, HW4).
- Corrected YanjuChen's HW 1 solutions for 4, 6, 18, 19.
- Removed LukasDresel's HW 1 test/solution for 9, since the provided parser doesn't accept it.
- Removed SeemantaSaha's HW 3 test/solution for 10, since the test case infinitely loops.
- Added HW 4's test cases (raw).
- Cleaned up HW 4's test cases to have consistent formatting (renaming files, capitalization of Even/Odd/Top, spacing, etc).
-  Fixed (perceived to be) incorrect HW 4 test cases, and added solutions to tests that didn't have solutions given. Slightly more detailed breakdown given below.

## Summary of HW 4 Fixes
- Added solutions for YifuLuo 0-20.
- Added solutions for abekarplus 13, 14, 15.
- chanijindal
    - fs: 2, 13, 17
    - notfs: 2, 9, 13, 18
- lukasdresel
    - both: 118
- nemanja
    - both: 1, 8, 12, 13, 15
- saagarjha
    - fs: 44
- seemantasaha
    - both: 9
- sydneyma
    - fs: 13, 24
    - notfs: 14

### CODE REVIEW

**Comment by zxybazh** [comment]
pending more tests...

**Comment by FourPieces** [comment]
Assignment 1 seems fine to me. 

I found two issues with assignment 3:
  - abekarplus-22 outputs `22 : 2, 2` when it should only output `22 : 2` since the second "2" reaching it is a duplicate state.
  - aprilcai-17 contains nondeterministic print statements, which aren't allowed.

I'll review assignment 4 and comment if I notice any other issues.

**Comment by FourPieces** [comment]
Found only one issue with the assignment 4 tests: I think saagarjha-fs-44.solution should read `Even`, not `Top`, since the while loop starts with `x` being odd, forcing only the true branch the first time around. Therefore, the print statement will only be reached after `x` has been set to `Even`.

**Comment by sidsenkumar11** [comment]
Hey, thanks for reviewing the tests. I'm not sure why the repo owner decided to merge when we had conflicts... but I'll still address them so sure we're on the same page.

- Concerning hw3/aprilcai-17, I agree that that test case should be removed. Thanks for noticing it.

- tldr of below: I still disagree with hw3/abekarplus-22.solution and hw4/saagarjha-fs-44.solution.

For hw3 (concrete transition system), the professor said we should not use collecting semantics. So, the only way two statements get merged is if both execute ***at the same time*** on the same line with the  same locals map and continuation stack. In abekarplus-22, this never happens. Here is my walkthrough of the state transition system for that test case: https://gist.github.com/sidsenkumar11/e3c28d106afc16b36beee889c00977b9. 

Unlike hw3, hw4 _does_ implement collecting semantics. In saagarjha-44.imp, the program only exits the while loop when the condition is even (concretely a zero). However, our abstract semantics isn't smart enough to see this - it's only smart enough to know when the condition should definitely be true (any odd number). On an even number (including "0"), the semantics doesn't know if the condition holds true because an even number could be 0 meaning false, or it could be 42 meaning true. So, we have to split into 2 paths here - one path where it is 0 and it reaches the print statement with `x = Even`, and another where it is a different even number and execution goes back into the while loop. Now, upon entering the while-loop, `x`could have been `Odd` (as before) but it also could have been `Even` as we've shown now, so the flow-sensitive analysis has to merge them to `x` incoming `Top`. Of course, when we get back to the while-loop condition again, Top has to go through both true and false paths, so we reach the "print" with x incoming "Top". Finally, since our solution is the flow-sensitive one, we have to print "Top".

Please let me know if you disagree with me about something; it's easy to mess up on this!

**Comment by zxybazh** [comment]
Hi, one of the students requested me to merge the pull request so that he may get a latest version of the current dataset. Please still feel free to send pull request if the conflict brings about any change in the testset.

**Comment by FourPieces** [comment]
Sid, looking at hw3/abekarplus-22 along with your state transitions (and my own), I see where the disagreement comes from - when you process the if/else state (your second transition), you turn the while into a `whileK`, whereas I turn it into a `stmtK(while)`. This causes yours to hit the print statement at two different times, whereas mine hits the print statement at the same time.

Can you double check your `toSK` helper function to see if you're turning whiles into `whileK`s in it? I think every statement passed to that helper function should become a `stmtK` instead.

I still need to double check what's going on with 4 - it's hard to reason about but I think you may be correct on that one.

**Comment by sidsenkumar11** [comment]
In the future, the student can directly pull the PR branch if he/she wants to use it. It kind of defeats the purpose of making a PR if you merge every request without vetting it; the master branch could have errors now that were introduced by my branch.

**Comment by sidsenkumar11** [comment]
@FourPieces Aha, you're right. My `toSK` implementation returns a `whileK`. I guess according to the transition diagram, it should first get wrapped into a `stmtK` first, and then unwrapped by rule . That was a good catch!

**Comment by FourPieces** [comment]
Glad it helped! Could you try incorporating that change into your Assignment 4 code and rerunning on saagarjha-44 and tell me if you get `Even` in that case as well?

Intuitively having `x` be top makes sense in the flow sensitive case, as the while guard gets processed both with x being even and odd. However, as far as the semantics go, it seems that the only time `while(x)` appears as the current statement for a state is when x=Odd. The x=Even locals map seems to never reach the guard during my manual run-throughs, and as a result x never gets merged to Top.

**Comment by sidsenkumar11** [comment]
I have to make semi-substantial changes to my code so it might be a while, but I'll try to review that case too by tonight.

**Comment by sidsenkumar11** [comment]
You were correct! I now get `Even` for saagarjha-fs-44.solution  as well. I'll make a new PR with all the fixes you mentioned here, thanks for catching them!

**Comment by aaabbbjj** [comment]
Hi all,
We have some disagreements on **no-fs** results for, siddarthsenthilkumar-14, siddarthsenthilkumar-15, siddarthsenthilkumar-23, siddarthsenthilkumar-25. 
Our results for 14 is:
10: even
15: odd
29: odd
31: even,

For 15
21: odd

For 23
11: even
20: even, odd
31: even
43: even
55: even, odd
64: even, odd

For 25
10: even, odd
22: even
34: even, odd
43: even, odd
52: odd

**Comment by FourPieces** [comment]
@aaabbbjj Looking over those test cases, I think I see where your confusion is coming from - you're evaluating the guards too concretely. Intuitively, when you encounter "Even = Odd", you think that evaluates to 0, so therefore the conditional branch should not hold.

However, it's important to remember with the abstract semantics that that "Even = Odd" does not evaluate to "0", but instead evaluates to "Even," which COULD be 0, but it also could be a non-zero (and thus "true") value as well. Therefore, when a guard has the form of "Even = Odd", both the true and false branches will still be executed as per the abstract semantics.

**Comment by aaabbbjj** [comment]
Another disagreement on fs solution for saagarjha-44 test case:
We got 11 : top.  Can someone confirm that?

**Pull request merged**
